# Generated by Django 3.1.5 on 2021-01-13 03:10

import api.user.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_customuser_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', api.user.models.UserManager()),
            ],
        ),
    ]
