version: '3.8'

services:
  db:
    container_name: postgres_database
    image: postgres
    env_file:
      - ./.env
  app:
    build: .
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    env_file:
      - ./.env
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    depends_on:
        - db
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "${PGADMIN_PORT}:80"
    restart: unless-stopped